# Generated by Django 4.2.5 on 2023-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание о нас')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание о нас')),
            ],
            options={
                'verbose_name': 'Учеьная программа',
                'verbose_name_plural': 'Учеьная программа',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройка'},
        ),
    ]
