# Generated by Django 4.2.5 on 2023-10-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_about_teach_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(default=1, verbose_name='Название сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Логотип сайта'),
            preserve_default=False,
        ),
    ]
