# Generated by Django 4.2.5 on 2023-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_settings_description_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
